### ISSUE TITLE
Modules mising?

### ISSUE THREAD

**Issue by wizzo-gmb** [deepsing-ai/deepsing#1]
`Traceback (most recent call last):
  File "C:\Users\Trading\Documents\NFT Utilities\deepsing-master\deepsing-master\deepsing.py", line 9, in <module>
    from utils.deep_sing import DeepSing
  File "C:\Users\Trading\Documents\NFT Utilities\deepsing-master\deepsing-master\utils\deep_sing.py", line 2, in <module>
    from utils.gan_utils import feedforward_gan
  File "C:\Users\Trading\Documents\NFT Utilities\deepsing-master\deepsing-master\utils\gan_utils.py", line 3, in <module>
    from utils.video_utils import torch_to_cv2
  File "C:\Users\Trading\Documents\NFT Utilities\deepsing-master\deepsing-master\utils\video_utils.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

am I missing something. Followed this install instructions.

**Comment by passalis** [comment]
Hi, you need to install [opencv](https://pypi.org/project/opencv-python/), i.e., more or less do a `pip install opencv-python` depending on your python installation and setup.
